modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/RagbeccaPlebs/TemplarsCore/issues"
[[mods]]
modId="templarscore"
version="${file.jarVersion}"
displayName="Templars Core"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://templarsofmortals.com"
#logoFile="examplemod.png"
credits="MakerTim, thanks for all the help"
authors="Ragbecca//Rebecca"
description='''
The Fundamental Core Of All The Coming Templars Mods
'''
[[dependencies.templarscore]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.templarscore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
